### ISSUE TITLE
deploy rc9 to nightly

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr-ops#70]
**Environment**
nightly

**Version**
[0.8.0-rc9](https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.0-rc9)

**Additional Details**

You will need to restart the blockchain:

```yaml
blockchain_configuration:

  # set the maximum block content size (in bytes)
  block_content_max_size: 253952
```

and remove the `bft_slots_ratio` if it was set
